name: Deploy Flask App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy files to server via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "."
        target: "/www/wwwroot/gameroom.uz"
        strip_components: 1

    - name: Setup environment and restart Flask app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /www/wwwroot/gameroom.uz

          # Virtual env mavjud bo‘lmasa yaratamiz
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate

          # .env faylni yozish
          cat <<EOF > .env
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_ADMIN_KEY=${{ secrets.SECRET_ADMIN_KEY }}
          EOF

          pip install --upgrade pip
          pip install -r requirements.txt

          # Flask app qayta ishga tushirish
          sudo systemctl restart flaskapp
